name: Cypress Tests
run-name: Cypress test on ${{ github.ref_name }} by ${{ github.actor }}
on:
  push:
    branches:
      - feature/changepassword/sira
jobs:
 cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install       
      - name: Cypress run
        uses: cypress-io/github-action@v2