name: Build Tests
run-name: Build test on ${{ github.ref_name }} by ${{ github.actor }}
on:
  push:
    branches:
      - feature/changepassword/sira
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Create Node environment
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Test build
        run: npm run build